<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMROGRAMAN**

**“Pengenalan Type Data dan Variabel Python”**

**Disusun Oleh :**

**Hafidh Laudza Mikhrad**

**2611532035**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Rifki Yuliandra**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum Pengenalan Type Data dan Variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis-jenis type data dan juga variabel yang ada di Python

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep mengenai macam-macam tipe data python dan bisa mengidentifiikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya yang ada pada bahasa pemrograman python

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

Hormat saya,

(Hafidh Laudza Mikhrad)

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang

Perkembangan teknologi informasi saat ini mendorong kebutuhan akan pengolahan data dan otomasi sistem yang cepat serta efisien. Dalam dunia pemrograman, bahasa Python menjadi salah satu bahasa yang sangat populer dan luas digunakan karena sintaksisnya yang sederhana, mudah dipahami, serta memiliki fleksibilitas tinggi untuk berbagai bidang seperti pengembangan perangkat lunak, analisis data, hingga kecerdasan buatan. Untuk membangun sebuah program yang fungsional di dalam Python, pemahaman mengenai konsep-konsep dasar pemrograman menjadi fondasi yang sangat krusial.

​Salah satu konsep paling mendasar dalam pemrograman adalah variabel. Dalam proses eksekusi kode, program membutuhkan mekanisme untuk menyimpan nilai atau data sementara di dalam memori komputer. Variabel bertindak sebagai penanda atau wadah berlabel yang memungkinkan pemrogram untuk menyimpan, mengakses, dan memanipulasi data tersebut di berbagai bagian dari alur program. Tanpa adanya variabel, pengolahan data secara dinamis akan sangat sulit dilakukan.

​Selain variabel, setiap data yang disimpan dan diproses memiliki karakteristik tertentu yang didefinisikan melalui tipe data. Tipe data dasar seperti integer (int), float (float), string (str), dan boolean (bool) menentukan jenis nilai yang dikandung serta operasi apa saja yang dapat dilakukan terhadap data tersebut. Berbeda dengan beberapa bahasa pemrograman lain yang mewajibkan deklarasi tipe data secara eksplisit, Python menggunakan sistem dynamic typing di mana tipe data ditentukan secara otomatis saat nilai diberikan. Meskipun memberikan kemudahan dan kecepatan dalam penulisan kode, karakteristik ini tetap menuntut pemrogram untuk memahami sifat tiap tipe data agar tidak terjadi kesalahan logika maupun operasional.

​Pemahaman mengenai variabel dan tipe data merupakan langkah awal yang wajib dikuasai sebelum mempelajari konsep pemrograman yang lebih kompleks, seperti struktur kendali, fungsi, maupun struktur data tingkat lanjut. Kesalahan dalam mengenali atau memanipulasi tipe data sering kali menjadi penyebab utama terjadinya galat (error) saat program dijalankan. Oleh karena itu, praktikum pengenalan variabel dan tipe data Python ini dilaksanakan agar praktikan dapat memahami secara langsung (hands-on) cara mendeklarasikan variabel, mengenali berbagai tipe data dasar, serta mengoperasikannya secara tepat dalam sintaksis bahasa Python.

## 1.2 Tujuan
1. Memahami Konsep Dasar Variabel.
2. Mengenali Jenis Tipe Data Variabel.
3. Mengimplementasikan Deklarasi dan Konversi Tipe Data.
4. Menganalisis dan Mengatasi Galat (Error).

## 1.3 Manfaat
1. Penguasaan Fondasi Pemrograman
2. Peningkatan Keterampilan Praktis (Hands-On)
3. Pencegahan Kesalahan Logika Kode

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

### 1. Pengenalan Bahasa Pemrograman Python

Python merupakan bahasa pemrograman tingkat tinggi (*high-level programming language*) yang bersifat *open-source*, terinterpretasi, dan berorientasi pada objek (*object-oriented*). Python dikenal dengan sintaksisnya yang bersih dan ringkas sehingga mengutamakan keterbacaan kode (*code readability*). Dalam praktiknya, Python mengadopsi mekanisme *dynamic typing*, yang berarti jenis tipe data pada suatu variabel didefinisikan secara otomatis oleh interpreter saat program dijalankan (*runtime*) sesuai dengan nilai yang diisikan ke dalamnya.

### 2. Konsep Variabel dan Tipe Data

Dalam pembuatan program, komputer membutuhkan lokasi memori untuk menyimpan informasi sementara:

* **Variabel** merupakan nama pengenal (*identifier*) atau wadah simbolis yang mengacu pada alokasi memori tertentu tempat data disimpan.
* **Tipe Data** adalah klasifikasi yang memberi tahu komputer mengenai jenis nilai yang dikandung oleh suatu variabel, sehingga komputer mengetahui jenis operasi matematika maupun logika apa yang dapat diterapkan pada data tersebut.

---

### 3. Tipe Data Skalar

Tipe data skalar (*primitive/scalar types*) adalah jenis tipe data paling dasar yang hanya mampu menampung satu nilai tunggal pada satu waktu.

#### A. Tipe Data Numerik (*Numeric Types*)

Tipe data numerik digunakan untuk menangani angka dan perhitungan matematis. Dalam Python, kelompok numerik terbagi menjadi tiga jenis:

1. **Integer (`int`)**: Menyimpan bilangan bulat positif maupun negatif tanpa koma atau desimal (contoh: `-10`, `0`, `100`).
2. **Float (`float`)**: Menyimpan bilangan riil yang memiliki titik desimal (*floating-point*) atau dituliskannya menggunakan notasi eksponensial (contoh: `3.14`, `-0.05`).
3. **Complex (`complex`)**: Menyimpan bilangan kompleks yang terdiri dari bagian riil dan bagian imajiner yang ditandai dengan sufiks `j` (contoh: `2 + 3j`).

#### B. Tipe Data Skalar Lainnya

1. **String (`str`)**: Kumpulan karakter atau teks yang diapit oleh tanda petik tunggal (`'`) atau ganda (`"`) (contoh: `"Praktikum Python"`).
2. **Boolean (`bool`)**: Tipe data logika yang hanya memiliki dua kemungkinan nilai, yaitu `True` (benar) atau `False` (salah).

---

### 4. Pengambilan Masukan Data (*Input Data*)

Dalam aplikasi interaktif, program membutuhkan masukan dari pengguna saat runtime:

* **Fungsi `input()`**: Digunakan untuk menangkap masukan teks yang diketikkan pengguna melalui konsol/terminal.
* **Sifat Bawaan**: Nilai yang dikembalikan oleh fungsi `input()` secara bawaan akan selalu bertipe data **String (`str`)**.
* **Konversi Tipe Data (*Type Casting*)**: Apabila data masukan pengguna hendak diolah dalam perhitungan matematis, data string tersebut harus dikonversi terlebih dahulu ke tipe numerik yang sesuai menggunakan fungsi penataan tipe seperti `int()` atau `float()`.

---

### 5. Konsep Konstanta (*Constants*)

**Konstanta** adalah jenis variabel khusus yang nilainya bersifat tetap dan idealnya tidak boleh diubah selama eksekusi program berjalan.

* Berbeda dengan bahasa pemrograman lain seperti Java atau C++, Python tidak menyediakan kata kunci (*keyword*) khusus untuk mengunci nilai variabel (seperti `const` atau `final`).
* Sebagai gantinya, komunitas Python menyepakati aturan konvensi standar (PEP 8) di mana penulisan nama variabel konstanta menggunakan **HURUF KAPITAL ENTIRELY** (contoh: `PI = 3.14159`, `GRAVITASI = 9.8`). Hal ini berfungsi sebagai penanda visual bagi pemrogram agar tidak mengubah isi variabel tersebut.

## 2.2 Kode Program

### 2.2.1 Program string "A_2611531019"

In [ ]:
nama_1019 = "Hafidh"
jenis_kelamin_1019 = 'L'
alamat_1019 = """
    Jln.Tui
    Kec.kuranji
    kota Padang
"""
agama_1019 = 'islam'
print("Nama saya adalah: ", nama_1019)
print("Jenis kelamin saya adalah: ", jenis_kelamin_1019)
print("Alamat saya adalah: ", alamat_1019)
print("Agama saya adalah ", agama_1019)

Nama saya adalah:  Hafidh
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Jln.Tui
    Kec.kuranji
    kota Padang

Agama saya adalah  islam


**Penjelasan :**
1. Baris pertama sampai delapan mendefinisikan variable ( `nama_1019, jenis_kelamin_1019, alamat_1019,dan agama_1019`) untuk menyimpan data identitas diri seperti nama, jenis kelamin, alamat (menggunakan multiline string), dan agama
2. Baris sembilan sampai dua belas berisi perintah `print()` untuk menampilkan atau mencetak nilai yang ada di dalam masing-masing variable tersebut ke layar konsol
3. Baris akhir menampilkan hasil (output) eksekusi program dimana teks dan data variable digabungkan dan dicetak secara berurutan sesuai dengan instruksi `print`

### 2.2.2 Program numerik "A_2611531019"

In [ ]:
a_1019=100
print("The type of variable having value", a_1019, "is", type(a_1019))

b_1019=10.2345
print("The type of variable having value", b_1019, "is", type(b_1019))

c_1019=100+3j
print("The type of variable having value", c_1019, "is", type(c_1019))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**
1. Pada baris pertama dan kedua terdapat variable `a_1019` bernilai `100` yang merupakan bilangan bulat, sehingga fungsi `type()` mengembalikan tipe data `<class 'int'>`
2. Pada baris keempat dan kelima terdapat variabel `b_1019` bernilai `10.2345` yang merupakan bilangan desimal, sehingga fungsi `type()` mengembalikan tipe data `<class 'float'>`
3. Pada baris ketujuh dan kedelapan terdapat variable `c_1019` bernilai `100+3j` yang merupakan bilangan kompleks (memiliki bagian riil dan imajiner `j`), sehingga fungsi `type()` mengembalikan tipe data `<class 'complex'>`

### 2.2.3 Program konstanta "A_2611531019"

In [ ]:
from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_1019 = float(input("Masukkan jari-jari: "))
luas_1019 = PI * jari_1019 * jari_1019
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1019, luas_1019))

pi: 3.140000
Luas lingkaran dengan jari-jari 21.00 adalah 1384.74


**Penjelasan :**
1. Baris pertama mengimpor `Final` dari modul `typing` untuk menandai suatu variable sebagai konstanta agar nilainya tidak diubah
2. Baris kedua mendeklarasikan konstanta `PI` dengan nilai `3.14` menggunakan tipe hint `Final`
3. Baris ketiga menampilkan nilai konstanta `PI` ke layar menggunakan format string `%f`
4. Baris keempat mengambil input jari-jari dari pengguna, lalu mengonversinya menjadi tipe data desimal (`float`) dan menyimpannya dalam variable `jari_1019`
5. Baris kelima menghitung luas linkaran dengan rumus PI * jari * jari dan menyimpannya ke dalam variable `luas_1019`
6. Baris keenam menampilkan hasil perhitungan luas lingkaran dengan format 2 angka di belakang koma (`%.2f`)

### 2.2.4 Program input "A_2611531019"

In [ ]:
panjang_1019 = input('Masukkan nilai panjang: ')
lebar_1019 = input('Masukkan nilai lebar: ')
luas_1019 = int(panjang_1019) * int(lebar_1019)
print("Luas =", luas_1019)

Luas = 18


**Penjelasan :**
1. Baris pertama menerima input nilai panjang dari pengguna dalam bentuk teks (string) dan menyimpannya ke dalam variabel `panjang_1019`
2. Baris kedua menerima input nilai lebar dari pengguna dalam bentuk teks dan menyimpannya ke dalam variable `lebar_1019`
3. Baris ketiga mengonversi nilai `panjang_1019` dan `lebar_1019` menjadi bilangan bulat (`int`), lalu mengalikannya untuk menghitung luas dan menyimpan hasilnya ke variable `luas_1019`
4. Baris keempat menampilkan teks `"luas = "` beserta nilai dari variable `luas_1019` ke layar


### 2.2.5 Program boolean "A_2611531019"

In [ ]:
is_lulus = True
is_cumlaude = True

nilai = 85
batas_lulus = 75

status_kelulusan = nilai >= batas_lulus

print("=== Check kelulusan ===")
print("Nilai:", nilai)
print("Apakah Lulus?:", status_kelulusan)
if is_lulus and is_cumlaude:
    print("Selamat, Anda lulus dengan predikat Cum Laude!")

=== Check kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cum Laude!


**Penjelasan :**
1. Baris pertama mendeklarasikan variable `is_lulus` dan `is_cumlaude` dengan nilai boolean `True`
2. Baris kedua mendeklarasikan variable `nilai` sebesar `85` dan `batas_lulus` sebesar `75`
3. Membandingkan apakah `nilai` lebih besar atau sama dengan `batas_lulus` ($85 \ge 75$), lalu menyimpannya ke variabel `status_kelulusan` yang menghasilkan nilai boolean `True`.
4. Menampilkan teks header, nilai dari variabel `nilai`, dan hasil dari `status_kelulusan` ke layar.
5. Mengevaluasi kondisi menggunakan operator logika `and`; karena kedua variabel `is_lulus` dan `is_cumlaude` bernilai `True`, pesan ucapan selamat lulus dengan predikat Cum Laude dicetak ke layar.

---
# BAB III
# KESIMPULAN



---
## DAFTAR PUSTAKA

[1] Microsoft, "Visual Studio Code Documentation," [Online]. Tersedia: https://code.visualstudio.com/docs [Diakses 2026].

[2] Python Software Foundation, "The Python Tutorial," [Online]. Tersedia: https://docs.python.org/3/tutorial/ [Diakses 2026].

[3] GitHub, Inc., "Getting Started with GitHub," [Online]. Tersedia: https://docs.github.com/en/get-started [Diakses 2026]